from __future__ import annotations

from typing import Any

class Client:
    @staticmethod
    async def connect(
        database_url: str,
        *,
        listener_url: str | None = None,
        max_query_connections: int = 10,
        max_listener_connections: int = 1,
    ) -> Client: ...
    async def migrate(self) -> None: ...
    async def enqueue(self, request: dict[str, Any]) -> tuple[str, bool]: ...
    async def enqueue_many(self, requests: list[dict[str, Any]]) -> list[tuple[str, bool]]: ...
    async def task_result(self, task_id: str) -> dict[str, Any] | None: ...
    async def wait_result(self, task_id: str, timeout: float | None) -> dict[str, Any] | None: ...
    async def emit_signal(self, task_id: str, name: str, occurrence: int, value: Any) -> Any: ...
    async def cancel(self, task_id: str) -> bool: ...

class TaskContext:
    async def step(self, name: str, occurrence: int, operation: Any) -> Any: ...
    async def sleep_for(self, name: str, occurrence: int, seconds: float) -> None: ...
    async def sleep_until(self, name: str, occurrence: int, wake_at: str) -> None: ...
    async def wait_for_signal(
        self,
        step_name: str,
        occurrence: int,
        signal_name: str,
        signal_occurrence: int = 0,
        timeout: float | None = None,
    ) -> Any: ...
    async def spawn(self, step_name: str, occurrence: int, request: dict[str, Any]) -> str: ...
    async def wait_for_result(
        self, step_name: str, occurrence: int, task_id: str, timeout: float | None = None
    ) -> Any: ...

class Worker:
    def __init__(self, database_url: str, queue_names: list[str], options: dict[str, Any]) -> None: ...
    def register(
        self,
        name: str,
        function: Any,
        handler_version: int = 1,
        retry_delay: float | None = 1.0,
    ) -> None: ...
    async def run(self) -> None: ...
    def shutdown(self) -> None: ...
